#!/usr/bin/env bash
# Copyright 2026 Jim Zucker
# SPDX-License-Identifier: LicenseRef-Proprietary
#
# Generate THIRD_PARTY_NOTICES.txt from Flutter's own build-time license output,
# so the committed third-party notices can never drift from what the app actually
# bundles. This is the Flutter-native equivalent of Android's oss-licenses-plugin
# or npm's license-checker. Run before a release.
#
#   ./scripts/gen_notices.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

echo "Building web to produce Flutter's aggregated license NOTICES..."
( cd app && flutter build web --release >/dev/null )

src="app/build/web/assets/NOTICES"
out="THIRD_PARTY_NOTICES.txt"
{
  echo "iHaveAnnuities — Third-Party Notices"
  echo "Auto-generated by scripts/gen_notices.sh from Flutter's build output."
  echo "Do not edit by hand. The app itself is proprietary (see LICENSE);"
  echo "the components below are used under their own open-source licenses."
  echo
  echo "========================================================================"
  echo
} > "$out"

if [ -f "${src}.gz" ]; then
  gunzip -c "${src}.gz" >> "$out"
elif [ -f "$src" ]; then
  cat "$src" >> "$out"
else
  echo "ERROR: $src not found — did 'flutter build web' succeed?" >&2
  exit 1
fi

echo "Wrote $out ($(wc -l < "$out" | tr -d ' ') lines, $(du -h "$out" | cut -f1))."
